#! /bin/sh
### BEGIN INIT INFO
# Provides:          single
# Required-Start:    $local_fs $all killprocs
# Required-Stop:
# Default-Start:     1
# Default-Stop:
# Short-Description: executed by init(8) upon entering runlevel 1 (single).
### END INIT INFO

PATH=/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

case "$1" in
  start)
	cd /opt/dmr && make start
	;;
  restart)
	cd /opt/dmr && make stop
	cd /opt/dmr && make start
	;;
  stop)
	cd /opt/dmr && make stop
	;;
  status)
	/usr/bin/docker ps
	;;
  *)
	echo "Usage: $0 start|stop|restart|status" >&2
	exit 3
	;;
esac
